# Generated by Django 5.0.3 on 2024-03-30 07:03

import market.models.product_model
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50, verbose_name='Категория')),
            ],
        ),
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50, verbose_name='Продукт')),
                ('product_image', models.ImageField(upload_to=market.models.product_model.directory_path, verbose_name='Картинка продукта')),
                ('product_description', models.CharField(max_length=500, verbose_name='Описание')),
                ('product_qty', models.PositiveIntegerField(verbose_name='Количество')),
                ('product_price', models.PositiveIntegerField(verbose_name='Цена')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='удалено')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата и время обновления')),
                ('deleted_at', models.DateTimeField(default=None, null=True, verbose_name='Дата и время удаления')),
                ('product_categories', models.ManyToManyField(blank=True, null=True, to='market.categorymodel', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
    ]
